spring.application.name=lms

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smart_library?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}

gemini.api.key=${GEMINI_KEY:put_your_key_here_for_local_testing}

server.port=${PORT:8082}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
