spring.application.name=lms

# Database Setup (Pulls secure variables from Render, falls back to local DB)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smart_library?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}

# NVIDIA NIM API Configuration
nvidia.nim.api.key=${NVIDIA_NIM_KEY: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}
nvidia.nim.model=meta/llama-3.2-11b-vision-instruct
# Render assigns a dynamic port. This allows Render to set the port, falling back to 8082 locally.
server.port=${PORT:8082}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect